# Generated by Django 2.1.5 on 2019-04-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='program',
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, to='main.ProgramInfo'),
        ),
    ]
