# Generated by Django 2.1.5 on 2019-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190404_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_program', to='main.ProgramInfo'),
        ),
    ]
