# Generated by Django 2.1.5 on 2019-04-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190410_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedprogram',
            options={'verbose_name': 'Разрешенная программа', 'verbose_name_plural': 'Разрешенные программы'},
        ),
    ]
